[2024-09-28T09:46:44.319+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-28T09:46:44.361+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag.run_insert_queries manual__2024-09-28T09:46:40.676725+00:00 [queued]>
[2024-09-28T09:46:44.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag.run_insert_queries manual__2024-09-28T09:46:40.676725+00:00 [queued]>
[2024-09-28T09:46:44.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-28T09:46:44.409+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): run_insert_queries> on 2024-09-28 09:46:40.676725+00:00
[2024-09-28T09:46:44.419+0000] {standard_task_runner.py:63} INFO - Started process 236 to run task
[2024-09-28T09:46:44.424+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag', 'run_insert_queries', 'manual__2024-09-28T09:46:40.676725+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/job.py', '--cfg-path', '/tmp/tmpyzrwanx6']
[2024-09-28T09:46:44.427+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask run_insert_queries
[2024-09-28T09:46:44.522+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres_dag.run_insert_queries manual__2024-09-28T09:46:40.676725+00:00 [running]> on host c39a3d3a6c9a
[2024-09-28T09:46:44.615+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'run_insert_queries', field 'sql'. Template: 'sample_files/insert_queries.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sample_files/insert_queries.sql
[2024-09-28T09:46:44.618+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sample_files/insert_queries.sql
[2024-09-28T09:46:44.632+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres_dag, task_id=run_insert_queries, run_id=manual__2024-09-28T09:46:40.676725+00:00, execution_date=20240928T094640, start_date=20240928T094644, end_date=20240928T094644
[2024-09-28T09:46:44.654+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task run_insert_queries (sample_files/insert_queries.sql; 236)
[2024-09-28T09:46:44.678+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-28T09:46:44.708+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T09:46:44.712+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
