[2024-09-28T09:24:54.556+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-28T09:24:54.623+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag.create_table manual__2024-09-28T09:24:52.518289+00:00 [queued]>
[2024-09-28T09:24:54.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag.create_table manual__2024-09-28T09:24:52.518289+00:00 [queued]>
[2024-09-28T09:24:54.636+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-28T09:24:54.652+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-09-28 09:24:52.518289+00:00
[2024-09-28T09:24:54.656+0000] {standard_task_runner.py:63} INFO - Started process 794 to run task
[2024-09-28T09:24:54.659+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag', 'create_table', 'manual__2024-09-28T09:24:52.518289+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/job.py', '--cfg-path', '/tmp/tmpw_perb6a']
[2024-09-28T09:24:54.661+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask create_table
[2024-09-28T09:24:54.714+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres_dag.create_table manual__2024-09-28T09:24:52.518289+00:00 [running]> on host 223b18cd90f2
[2024-09-28T09:24:54.823+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-28T09:24:52.518289+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-28T09:24:52.518289+00:00'
[2024-09-28T09:24:54.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-28T09:24:54.861+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS sample_table (
            id SERIAL PRIMARY KEY,
            column1 VARCHAR(50),
            column2 INT,
            column3 DATE
        );
        
[2024-09-28T09:24:54.873+0000] {base.py:84} INFO - Using connection ID 'write_to_psql' for task execution.
[2024-09-28T09:24:54.888+0000] {base.py:84} INFO - Using connection ID 'write_to_psql' for task execution.
[2024-09-28T09:24:54.895+0000] {sql.py:470} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sample_table (
            id SERIAL PRIMARY KEY,
            column1 VARCHAR(50),
            column2 INT,
            column3 DATE
        );
        , parameters: None
[2024-09-28T09:24:54.904+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-28T09:24:54.905+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(sample_table_id_seq, 2200) already exists.

[2024-09-28T09:24:54.916+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres_dag, task_id=create_table, run_id=manual__2024-09-28T09:24:52.518289+00:00, execution_date=20240928T092452, start_date=20240928T092454, end_date=20240928T092454
[2024-09-28T09:24:54.927+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task create_table (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(sample_table_id_seq, 2200) already exists.
; 794)
[2024-09-28T09:24:54.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-28T09:24:54.972+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T09:24:54.973+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
