[2024-09-28T09:37:10.793+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-28T09:37:10.837+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag.run_insert_queries manual__2024-09-28T09:37:04.590790+00:00 [queued]>
[2024-09-28T09:37:10.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag.run_insert_queries manual__2024-09-28T09:37:04.590790+00:00 [queued]>
[2024-09-28T09:37:10.851+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-28T09:37:10.872+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): run_insert_queries> on 2024-09-28 09:37:04.590790+00:00
[2024-09-28T09:37:10.881+0000] {standard_task_runner.py:63} INFO - Started process 1290 to run task
[2024-09-28T09:37:10.885+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag', 'run_insert_queries', 'manual__2024-09-28T09:37:04.590790+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/job.py', '--cfg-path', '/tmp/tmpp7qfkv_i']
[2024-09-28T09:37:10.888+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask run_insert_queries
[2024-09-28T09:37:10.954+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres_dag.run_insert_queries manual__2024-09-28T09:37:04.590790+00:00 [running]> on host 223b18cd90f2
[2024-09-28T09:37:11.013+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'run_insert_queries', field 'sql'. Template: '/opt/***/sample_files/insert_queries.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sample_files/insert_queries.sql
[2024-09-28T09:37:11.015+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sample_files/insert_queries.sql
[2024-09-28T09:37:11.028+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres_dag, task_id=run_insert_queries, run_id=manual__2024-09-28T09:37:04.590790+00:00, execution_date=20240928T093704, start_date=20240928T093710, end_date=20240928T093711
[2024-09-28T09:37:11.044+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task run_insert_queries (/opt/airflow/sample_files/insert_queries.sql; 1290)
[2024-09-28T09:37:11.059+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-28T09:37:11.081+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T09:37:11.083+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
