[2024-09-28T11:55:24.706+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-28T11:55:24.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag.run_insert_queries scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-09-28T11:55:24.767+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag.run_insert_queries scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-09-28T11:55:24.768+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-28T11:55:24.795+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): run_insert_queries> on 2024-01-01 00:00:00+00:00
[2024-09-28T11:55:24.804+0000] {standard_task_runner.py:63} INFO - Started process 3427 to run task
[2024-09-28T11:55:24.808+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag', 'run_insert_queries', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/job.py', '--cfg-path', '/tmp/tmp7ao6u6dh']
[2024-09-28T11:55:24.811+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask run_insert_queries
[2024-09-28T11:55:24.874+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres_dag.run_insert_queries scheduled__2024-01-01T00:00:00+00:00 [running]> on host c39a3d3a6c9a
[2024-09-28T11:55:24.974+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag' AIRFLOW_CTX_TASK_ID='run_insert_queries' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-09-28T11:55:24.976+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-28T11:55:24.990+0000] {sql.py:276} INFO - Executing: INSERT INTO sample_table (id, name, age) VALUES (1, 'John Doe', 30);
INSERT INTO sample_table (id, name, age) VALUES (2, 'Jane Smith', 25);
INSERT INTO sample_table (id, name, age) VALUES (3, 'Bob Johnson', 22);
[2024-09-28T11:55:25.002+0000] {base.py:84} INFO - Using connection ID 'write_to_psql' for task execution.
[2024-09-28T11:55:25.015+0000] {base.py:84} INFO - Using connection ID 'write_to_psql' for task execution.
[2024-09-28T11:55:25.022+0000] {sql.py:470} INFO - Running statement: INSERT INTO sample_table (id, name, age) VALUES (1, 'John Doe', 30);
INSERT INTO sample_table (id, name, age) VALUES (2, 'Jane Smith', 25);
INSERT INTO sample_table (id, name, age) VALUES (3, 'Bob Johnson', 22);, parameters: None
[2024-09-28T11:55:25.029+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-28T11:55:25.030+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "sample_table_pkey"
DETAIL:  Key (id)=(1) already exists.

[2024-09-28T11:55:25.041+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres_dag, task_id=run_insert_queries, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240928T115524, end_date=20240928T115525
[2024-09-28T11:55:25.055+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task run_insert_queries (duplicate key value violates unique constraint "sample_table_pkey"
DETAIL:  Key (id)=(1) already exists.
; 3427)
[2024-09-28T11:55:25.102+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-28T11:55:25.121+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T11:55:25.124+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
